import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserDailyPerformance1773626836421 implements MigrationInterface {
    name = 'AddUserDailyPerformance1773626836421'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_daily_performance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "row_number" integer NOT NULL, "date" date NOT NULL, "metropolitan_area" character varying(255) NOT NULL, "user_id" character varying(255) NOT NULL, "city_name" character varying(255) NOT NULL, "auditor_name" character varying(255) NOT NULL, "total_pos" integer NOT NULL, "approved_pos" integer NOT NULL, "partially_rejected_pos" integer NOT NULL, "rejected_pos" integer NOT NULL, "in_qc_pos" integer NOT NULL, "incomplete_pos" integer NOT NULL, "refusal_pos" integer NOT NULL, "visited_microzones" integer NOT NULL, "first_task_time" TIME NOT NULL, "last_task_time" TIME NOT NULL, "time_in_forms_hours" numeric(10,2) NOT NULL, "time_walking_hours" numeric(10,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e2f8dcb5397679ec4a739b7f622" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "identity_number" character varying(100) NOT NULL, "country" character varying(150) NOT NULL, "area" character varying(150) NOT NULL, "city" character varying(150) NOT NULL, "birth_date" date NOT NULL, "address" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(50) NOT NULL, "status" character varying(100) NOT NULL, "time" character varying(100) NOT NULL, "project" character varying(255) NOT NULL, "staff_type" character varying(100) NOT NULL, "unnamed_14" character varying(255), "contacted" boolean NOT NULL, "supervisor" character varying(255) NOT NULL, "entry_date" date NOT NULL, "entry_month" character varying(50) NOT NULL, "today" date NOT NULL, "seniority_days" integer NOT NULL, "level" character varying(100) NOT NULL, "wpp" character varying(100) NOT NULL, "inv" character varying(100) NOT NULL, "exit_date" date, "exit_month" character varying(50), "worked_days" integer NOT NULL, "exit_reason" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_545877cd25d512cc9d9e96ec69b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "simplified_city" character varying(255) NOT NULL, "cities" character varying(255) NOT NULL, "mo" character varying(255) NOT NULL, "breaks" character varying(255) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fac830e7b2f832e5fc71352847e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "historical_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "row_number" integer NOT NULL, "submitted_date" date NOT NULL, "city_name" character varying(255) NOT NULL, "auditor_name" character varying(255) NOT NULL, "place_id" character varying(255) NOT NULL, "purchase_diaries" integer NOT NULL, "total_invoice_collected" integer NOT NULL, "total_pos_collected" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d6303a200d1d9dc8f3bcb857331" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edge_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "metropolitan_area" character varying(255) NOT NULL, "city_name" character varying(255) NOT NULL, "mo" character varying(255) NOT NULL, "simplified_city" character varying(255) NOT NULL, "breaks" character varying(255) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_784fa349f22cdf37d1c751a5597" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_performance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "row_number" integer NOT NULL, "auditor_name" character varying(255) NOT NULL, "date" date NOT NULL, "metropolitan_area" character varying(255) NOT NULL, "city_name" character varying(255) NOT NULL, "user_id" character varying(255) NOT NULL, "visits_for_recruitment" integer NOT NULL, "pos_recruited" integer NOT NULL, "visits_for_invoice_collection" integer NOT NULL, "first_task_time" TIME NOT NULL, "last_task_time" TIME NOT NULL, "visits_with_invoice_collection" integer NOT NULL, "visits_with_invoice_and_approved_census" integer NOT NULL, "visits_with_invoice_and_incomplete_census" integer NOT NULL, "visits_with_invoice_and_rejected_census" integer NOT NULL, "visits_with_pending_qc_census" integer NOT NULL, "visits_with_rejected_invoice_and_approved_census" integer NOT NULL, "approved_census_collected_in_invoice_bundle" integer NOT NULL, "recruitment_rate" numeric(10,2) NOT NULL, "time_in_forms_hours" numeric(10,2) NOT NULL, "time_walking_hours" numeric(10,2) NOT NULL, "invoice_collection_rate" numeric(10,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0d48413d196045d945fc762fc04" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "daily_performance"`);
        await queryRunner.query(`DROP TABLE "edge_configurations"`);
        await queryRunner.query(`DROP TABLE "historical_data"`);
        await queryRunner.query(`DROP TABLE "invoice_configurations"`);
        await queryRunner.query(`DROP TABLE "system_registrations"`);
        await queryRunner.query(`DROP TABLE "user_daily_performance"`);
    }

}
